"""initial migration

Revision ID: 6eb36817015a
Revises: 
Create Date: 2025-05-28 18:26:10.211942

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6eb36817015a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    schema='rms'
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('identity_verified', sa.Boolean(), nullable=True),
    sa.Column('profile_image', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='rms'
    )
    with op.batch_alter_table('users', schema='rms') as batch_op:
        batch_op.create_index(batch_op.f('ix_rms_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_rms_users_phone'), ['phone'], unique=True)

    op.create_table('user_roles',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['rms.roles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['rms.users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'role_id'),
    schema='rms'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_roles', schema='rms')
    with op.batch_alter_table('users', schema='rms') as batch_op:
        batch_op.drop_index(batch_op.f('ix_rms_users_phone'))
        batch_op.drop_index(batch_op.f('ix_rms_users_email'))

    op.drop_table('users', schema='rms')
    op.drop_table('roles', schema='rms')
    # ### end Alembic commands ###
